In [2]:
import pandas as pd

customers = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/olist_customers_dataset.csv")

orders = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/olist_orders_dataset.csv")

order_items = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/olist_order_items_dataset.csv")

order_payments = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/olist_order_payments_dataset.csv")

In [4]:
order_reviews = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/olist_order_reviews_dataset.csv")

products = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/olist_products_dataset.csv")

sellers = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/olist_sellers_dataset.csv")

geolocation = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/olist_geolocation_dataset.csv")

category_translation = pd.read_csv("C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Raw/product_category_name_translation.csv")

In [6]:
# reviewing Customers
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [3]:
customers.shape

(99441, 5)

In [4]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [6]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  object
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

In [5]:
customers.describe

<bound method NDFrame.describe of                             customer_id                customer_unique_id  \
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
...                                 ...                               ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix          customer_city customer_state
0                         14409                 franca             SP
1                          9790  sao bernardo do campo             SP
2                          1151              sao paulo             SP
3                          8775        mogi das cruzes             SP
4                         13056               campinas             SP
...                         ...                    ...            ...
99436                      3937              sao paulo             SP
99437                      6764        taboao da serra             SP
99438                     60115              fortaleza             CE
99439                     92120                 canoas             RS
99440                      6703                  cotia             SP

[99441 rows x 5 columns]>

In [16]:
customers.describe()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441,99441,99441
unique,99441,96096,14994,4119,27
top,274fa6071e5e17fe303b9748641082c8,8d50f5eadf50201ccdcedfb9e2ac8455,22790,sao paulo,SP
freq,1,17,142,15540,41746

In [8]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [9]:
customers.duplicated().sum()

np.int64(0)

In [3]:
customers['customer_unique_id'].value_counts()

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
1b6c7548a2a1f9037c1fd3ddfed95f33     7
                                    ..
1c137fe37df712015f6488edafe8ece4     1
5a1680640123fc80e801301a2fb57395     1
046470763123d3d6364f89095b4e47ab     1
aaf22868003377e859049dcf5f0b3fdf     1
206e64e8af2633a2ebe158a7fcb860db     1
Name: count, Length: 96096, dtype: int64

In [5]:
#problem 1: Fixing the "Leading Zero" Zip Code Trap
# Convert to string and pad with leading zeros up to 5 characters
customers['customer_zip_code_prefix'] = customers['customer_zip_code_prefix'].astype(str).str.zfill(5)

# Verify the fix
print(customers['customer_zip_code_prefix'].head())

0    14409
1    09790
2    01151
3    08775
4    13056
Name: customer_zip_code_prefix, dtype: object

In [7]:
#problem 2: Standardizing the City Names
# Step A: Convert everything to lowercase
customers['customer_city'] = customers['customer_city'].str.lower()

# Step B: Strip out all the special accents (ã, é, etc.)
customers['customer_city'] = customers['customer_city'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

# Verify the fix by looking at the top 5 cities
print(customers['customer_city'].value_counts().head())

customer_city
sao paulo         15540
rio de janeiro     6882
belo horizonte     2773
brasilia           2131
curitiba           1521
Name: count, dtype: int64

In [8]:
#problem 3: Handling the "Unique" Customer Illusion
# Count unique human beings
true_customer_count = customers['customer_unique_id'].nunique()
print(f"Total real human customers: {true_customer_count}")

Total real human customers: 96096

In [15]:
# Create a new dataframe containing only one record per human
cleaned_customers = customers.drop_duplicates(subset=['customer_unique_id'])

# Check how many rows were dropped
print(f"Original rows: {len(customers)}")
print(f"Unique human rows: {len(unique_people_df)}")

Original rows: 99441
Unique human rows: 96096

In [10]:
99441-96096

3345

In [14]:
import os

# Define your output directory (switching from 'Raw' to 'Cleaned')
cleaned_dir = "C:/Users/Dell/Desktop/projects/Data_Analyst_Project1/DATA/Cleaned/"

# Create the folder if it doesn't exist yet
os.makedirs(cleaned_dir, exist_ok=True)

# 1. Save the full cleaned dataset (99,441 rows)
customers.to_csv(cleaned_dir + "cleaned_customers_all.csv", index=False)

# 2. Save the deduplicated unique customer dataset (96,096 rows)
cleaned_customers.to_csv(cleaned_dir + "cleaned_customers_unique.csv", index=False)

print("Datasets successfully saved as CSV!")

Datasets successfully saved as CSV!